name: Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version: 18.14.2
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version: 18.14.2
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test:ci

  build:
    name: Build
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version: 18.14.2
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@v3
        if: success() && github.ref == 'refs/heads/main'
        with:
          name: package
          path: dist

  release:
    name: Release
    if: success() && github.ref == 'refs/heads/main'
    needs: build
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version: 18.14.2
          registry-url: https://registry.npmjs.org/
      - name: Configure git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Configure npm
        run: npm config set //registry.npmjs.org/:_authToken ${{secrets.WCP_NPM_TOKEN}}
      - name: Install dependencies
        run: npm ci
      - name: Release
        run: npx release-it --no-npm.publish --ci
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NODE_AUTH_TOKEN: ${{secrets.WCP_NPM_TOKEN}}
      - name: Rebuild tag
        run: npm run build
      - uses: actions/upload-artifact@v3
        if: success() && github.ref == 'refs/heads/main'
        with:
          name: package
          path: dist

  publish:
    name: Publish
    if: success() && github.ref == 'refs/heads/main'
    needs: release
    runs-on: ubuntu-latest
    strategy:
      matrix: { dir: ["cem-plugin-examples", "cem-plugin-inline-readme"] }
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version: 18.14.2
          registry-url: https://registry.npmjs.org/
      - uses: actions/download-artifact@v3
        with:
          name: package
          path: dist
      - name: Configure npm
        run: npm config set //registry.npmjs.org/:_authToken ${{secrets.WCP_NPM_TOKEN}}
      - name: Release package
        working-directory: dist/${{matrix.dir}}
        run: npx release-it --no-git --ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.WCP_NPM_TOKEN}}
